name: your_project_name
description: A new Flutter project.

# The following line prevents the package from being accidentally published to pub.dev using pub publish.
# This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  # Add the firebase_core and firebase_auth packages
  firebase_auth: ^5.1.2
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.1.1
  webview_flutter: ^4.2.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  image_picker: ^1.1.2
  path_provider: ^2.0.5
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  url_launcher_web: ^2.0.5
  intl: ^0.19.0
  http: ^1.2.1
  flutter_secure_storage: ^9.2.2
  font_awesome_flutter: ^10.7.0
  fluttertoast: ^8.2.6
  vibration: ^1.9.0
  whatsapp_unilink: ^2.1.0
  firebase_messaging: ^15.0.4






dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/saint_george.png"




flutter:
  uses-material-design: true
  assets:
    - assets/bg_kenisa.jpg
    - assets/img.png
    - assets/st_george.png
    - assets/img_1.png
    - assets/cross.png
    - assets/logo_el_group.png